kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.deployment_name}}
  labels:
    app: {{ .Values.deployment_name}}
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: {{ .Values.deployment_name}}

---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ .Values.deployment_name}}
  labels:
    app: {{ .Values.deployment_name}}
spec:
  port:
    targetPort: http
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: {{ .Values.deployment_name}}
    weight: 100
  wildcardPolicy: None