kind: Route
apiVersion: route.openshift.io/v1
metadata:
  annotations:
    openshift.io/host.generated: 'true'
  name: el-{{ .Values.pipeline_name }}-trigger-route
  labels:
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    eventlistener: {{ .Values.pipeline_name }}-trigger-event-listener
spec:
  to:
    kind: Service
    name: el-{{ .Values.pipeline_name }}-trigger-event-listener
    weight: 100
  port:
    targetPort: 8080
  wildcardPolicy: None
