apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: image-registry
spec:
  params:
    - name: url
      value: >-
        image-registry.openshift-image-registry.svc:5000/{{ .Release.Namespace }}/{{ .Values.image_stream_name }}
  type: image
